trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
  - job: MSYS
    timeoutInMinutes: 360
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 5
      matrix:
        x86_64:
          MSYS_DIR: msys64
          BASE_REPO: msys2-ci-base
    steps:
      - powershell: |
          (New-Object Net.WebClient).DownloadFile("https://github.com/msys2/msys2-installer/releases/download/2020-05-22/msys2-base-x86_64-20200522.sfx.exe", "sfx.exe")
        displayName: Download MSYS2
      - script: |
          sfx.exe -y -o%CD:~0,2%\
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\bash -lc ""
        displayName: Extract/Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\$(MSYS_DIR)\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm -Syuu
        displayName: Update MSYS2
      - script: |
          set PATH=%CD:~0,2%\$(MSYS_DIR)\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm --needed -S git base base-devel msys2-devel
        displayName: Install Toolchain
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\bash -lc "bash ci-build.sh"
        displayName: CI-Build
        env:
          MSYSTEM: MSYS
          CHERE_INVOKING: yes
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_ACCOUNT: msys2
          PACMAN_REPOSITORY_NAME: ci.msys
      - task: PublishBuildArtifacts@1
        displayName: Publish packages
        continueOnError: true
        condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/artifacts
          artifactName: $(MSYS_DIR)
