name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v1
        with:
          msystem: MSYSTEM
          install: git base-devel msys2-devel
          update: true

      - name: CI-Build
        run: ./ci-build.sh
